esphome:
  name: "esp32cam"
  friendly_name: ESP32 Cam AI

esp32:
  board: esp32cam
  framework:
    type: esp-idf
   

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

psram:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.86.79
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32cam-ai Fallback Hotspot"
    password: "IFR1wnyILavM"

captive_portal:


esp32_camera:
  external_clock:
    pin: GPIO21
    frequency: 8MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  vertical_flip: False
  horizontal_mirror: False


  # Image settings
  name: My Camera



switch:
  - platform: shutdown
    name: "esp32cam Shutdown"
    restore_mode: ALWAYS_OFF

  - platform: restart
    name: "esp32cam Restart"
    restore_mode: ALWAYS_OFF    

# Example configuration entry
debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    psram:
      name: "Free PSRAM"
